### ISSUE TITLE
Nem/ritkan fordul a frontend

### ISSUE THREAD

**Issue by szaszm** [bme-db-lab/szglab5-frontend#7]
Ezt kaptam a fecske-dev-en, azota Marknak elojott a helyi gepen is. Neha sikerul a build, neha nem. Eleg miszterikus.
Log:
```
frontend@fecske-dev:~$ ember build --environment production                                                                                                   
WARNING: Node v8.4.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js.             
Could not start watchman                                                                                                                                      
Visit https://ember-cli.com/user-guide/#watchman for more info.                                                                                               
cleaning up...                                                                                                                                                
Build failed.                                                                                                                                                 
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (addons)] failed with:                                                                                   
SyntaxError: modules/ember-uploader/uploaders/base.js: Unexpected token (192:6)                                                                               
  190 |                                                                                                                                                       
  191 |     return this.ajaxPromise({                                                                                                                         
> 192 |       ...ajaxSettings,                                                                                                                                
      |       ^                                                                                                                                               
  193 |       contentType: false,                                                                                                                             
  194 |       processData: false,                                                                                                                             
  195 |       xhr: () => {                                                                                                                                    
    at Parser.pp$5.raise (/srv/http/szglab5-frontend/node_modules/ember-cli-babel/node_modules/babylon/lib/index.js:4454:13)                                  
    at Parser.pp.unexpected (/srv/http/szglab5-frontend/node_modules/ember-cli-babel/node_modules/babylon/lib/index.js:1761:8)                                
    at Parser.pp$3.parseIdentifier (/srv/http/szglab5-frontend/node_modules/ember-cli-babel/node_modules/babylon/lib/index.js:4332:10)                        
    at Parser.pp$3.parsePropertyName (/srv/http/szglab5-frontend/node_modules/ember-cli-babel/node_modules/babylon/lib/index.js:4156:96)                      
    at Parser.pp$3.parseObj (/srv/http/szglab5-frontend/node_modules/ember-cli-babel/node_modules/babylon/lib/index.js:4045:12)                               
    at Parser.pp$3.parseExprAtom (/srv/http/szglab5-frontend/node_modules/ember-cli-babel/node_modules/babylon/lib/index.js:3719:19)                          
    at Parser.pp$3.parseExprSubscripts (/srv/http/szglab5-frontend/node_modules/ember-cli-babel/node_modules/babylon/lib/index.js:3494:19)                    
    at Parser.pp$3.parseMaybeUnary (/srv/http/szglab5-frontend/node_modules/ember-cli-babel/node_modules/babylon/lib/index.js:3474:19)                        
    at Parser.pp$3.parseExprOps (/srv/http/szglab5-frontend/node_modules/ember-cli-babel/node_modules/babylon/lib/index.js:3404:19)                           
    at Parser.pp$3.parseMaybeConditional (/srv/http/szglab5-frontend/node_modules/ember-cli-babel/node_modules/babylon/lib/index.js:3381:19)                  
                                                                                                                                                              
The broccoli plugin was instantiated at: 
    at BroccoliMergeTrees.Plugin (/srv/http/szglab5-frontend/node_modules/broccoli-plugin/index.js:7:31)                                                      
    at new BroccoliMergeTrees (/srv/http/szglab5-frontend/node_modules/broccoli-merge-trees/index.js:42:10)                                                   
    at BroccoliMergeTrees (/srv/http/szglab5-frontend/node_modules/broccoli-merge-trees/index.js:36:53)                                                       
    at mergeTrees (/srv/http/szglab5-frontend/node_modules/ember-cli/lib/broccoli/merge-trees.js:46:18)                                                       
    at EmberApp._addonTree (/srv/http/szglab5-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:929:20)                                               
    at EmberApp._processedVendorTree (/srv/http/szglab5-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:974:20)                                     
    at EmberApp._processedExternalTree (/srv/http/szglab5-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1005:21)                                  
    at EmberApp.appAndDependencies (/srv/http/szglab5-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1114:30)                                      
    at EmberApp.javascript (/srv/http/szglab5-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1244:34)                                              
    at EmberApp.toArray (/srv/http/szglab5-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1674:10)                                  
```
mar volt:
`npm install`
`bower install`
`rm -rf node_modules && npm install`

**Comment by lordblendi** [comment]
A projekt ember-cli verzioja tul regi, nincs tesztelve 8-as node-al, ahogy a warning is irja. Node 6.11.2-vel nalam gond nelkul fordul, de 8.4-en ugyanez a hiba, mint nektek.

Ket megoldast tudok javasolni:
1. ne hasznaljatok 8-as node-ot a frontendhez, hanem a mostani LTS verzioval dolgozzatok (6.11.2 jelenleg)
2. frissitsetek a frontend Ember verziojat, mert elegge le van maradva a mostaniakhoz kepest.

Ha van idotok, akkor en mindenkeppen a frissitest javaslom, szeptember 18 utan tudok is benne segiteni. Utobbival kapcsolatban:

#### ember-cli
A frontend jelenleg 2.11.1-es ember-cli-t hasznal, ami eleg regi, azota kiadtak jo par verziot (a betakat nem nezve):

1. "2.12.0"
2. "2.12.1"
3. "2.12.2"
4. "2.12.3"
5. "2.13.0"
6. "2.13.1"
7. "2.13.2"
8. "2.13.3"
9. "2.14.0"
10. "2.14.1"
11. "2.14.2"
12. "2.15.0"

A listazashoz hasznalhatjatok a `npm view ember-cli versions --json` parancsot. A 2.14.2 jol mukodik, a 2.15-ot meg nem hasznaltam. 

#### ember-data

Frontend jelenleg hasznalt verzioja: 2.11.0 eredetileg (ezt mult heten frissitetten 2.13.1-re a 6-os babellel egyutt). Azota megjelentek (betak nelkul):

1.   "2.11.1",
2.   "2.11.2",
3.   "2.11.3",
4.   "2.12.0",
5.   "2.12.1",
6.   "2.12.2",
7.   "2.13.0",
8.   "2.13.1",
9.   "2.13.2",
10.   "2.14.0",
11.   "2.14.1",
12.   "2.14.2",
13.   "2.14.3",
14.   "2.14.4",
15.   "2.14.5",
16.   "2.14.6",
17.   "2.14.7",
18.   "2.14.8",
19.   "2.14.9",
20.   "2.14.10",
21.   "2.14.11",
22.   "2.15.0"


A 2.14 eleji Ember-data-nal volt egy bug a relationokben (azt mar javitottak), azokkal vigyazzatok:

- https://github.com/emberjs/data/issues/4942 
- https://github.com/emberjs/data/issues/5023


A listazashoz hasznalhatjatok a `npm view ember-data versions --json` parancsot Ember-data-bol pedig 2.14.10 volt amit utoljara teszteltem, az jo volt.

#### ember updateles:
En frissiteni az [ember-cli-update](https://github.com/kellyselden/ember-cli-update) tool-al szoktam. Alapvetoen az updateles nem veszes, par dolgot kell merge-elni, par perc alatt megvan. A package nevnel kell vigyazni, illetve a package.json-ben a kulonbozo addon-ok verzioira. 

A masik megoldas az [ember-cli update notes kovetese](https://github.com/ember-cli/ember-cli/releases).

A gond akkor jon, hogyha a kulonbozo addon-ok nem tamogatjak a legujabb Ember verziokat (mert mondjuk aki irta, mar nem torodik vele). Amig van frissitett verzio, ami mukodik, addig jo, rosszabb esetben uj addont kell keresni/irni.

Pl kapasbol a [package.json](https://github.com/bme-db-lab/szglab5-frontend/blob/master/package.json#L45) 45. soraban levo ember-promise-helper el fog halni build kozben az await miatt, abbol az 1.0.3-mat kell hasznalni.

**Comment by Kisfejes** [comment]
nekem egy frissen leszedett reponál ez segitett:
-npm install
-bower install
-npm install

**Comment by lordblendi** [comment]
@szaszm hogy oldottad meg vegul? van valami update ezzel kapcsolatban?

**Comment by csutorasr** [comment]
O is ugyanezt futtatja, mint ahogy mindenki. Az ember-data-t mindenhonnan kiszedtuk, rollbackeltunk, ugy sem ment, utana visszaraktuk az sem segitett. Ez a mesterharmas fogas bevalt es megy.

**Comment by lordblendi** [comment]
A fenti log is jelzi, hogy a hiba nem az ember-data-ban van, hanem az egyik addonban.

> `SyntaxError: modules/ember-uploader/uploaders/base.js: Unexpected token (192:6)   `

**Comment by csutorasr** [comment]
Bocsi elirtam, ember-uploader-t akartam irni.

**Comment by csutorasr** [comment]
```
WARNING: Node v8.1.2 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js.

Running without elevated rights. Running Ember CLI "as Administrator" increases performance significantly.
See ember-cli.com/user-guide/#windows for details.

Livereload server on http://localhost:49153
Serving on http://localhost:4200/
The Broccoli Plugin: [ConfigReplace] failed with:
Error: ENOENT: no such file or directory, lstat 'C:\Users\Csuto\Documents\projects\szglab5-main\frontend\tmp\funnel-input_base_path-czKcxCk3.tmp\index.html'
    at Object.fs.lstatSync (fs.js:946:11)
    at symlinkWindows (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\symlink-or-copy\index.js:106:25)
    at Function.symlinkOrCopySync [as sync] (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\symlink-or-copy\index.js:63:5)
    at Funnel._copy (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\broccoli-funnel\index.js:492:19)
    at Funnel.processFile (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\broccoli-funnel\index.js:475:8)
    at Funnel.applyPatch [as _applyPatch] (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\broccoli-funnel\index.js:389:12)
    at Funnel.<anonymous> (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\broccoli-funnel\index.js:343:10)
    at Array.forEach (native)
    at Funnel.processFilters (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\broccoli-funnel\index.js:342:11)
    at Funnel.build (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\broccoli-funnel\index.js:258:10)

The broccoli plugin was instantiated at:
    at ConfigReplace.Plugin (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\broccoli-plugin\index.js:7:31)
    at new ConfigReplace (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\broccoli-config-replace\index.js:13:10)
    at EmberApp.testIndex (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\ember-cli\lib\broccoli\ember-app.js:782:10)
    at EmberApp.toArray (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\ember-cli\lib\broccoli\ember-app.js:1681:43)
    at EmberApp.toTree (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\ember-cli\lib\broccoli\ember-app.js:1696:30)
    at module.exports (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\ember-cli-build.js:26:14)
    at Class.setupBroccoliBuilder (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\ember-cli\lib\models\builder.js:84:19)
    at Class.init (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\ember-cli\lib\models\builder.js:64:10)
    at Class.superWrapper [as init] (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\ember-cli\node_modules\core-object\lib\assign-properties.js:32:18)
    at Class (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\ember-cli\node_modules\core-object\core-object.js:32:33)


```

Ez a masik kedvencem. Es ezt nem tudtuk sehogy sem megoldani.

A legujabb egy css sort valtoztato commitod utan tortent.

**Comment by lordblendi** [comment]
Ilyen hibauzenetet meg sosem lattam. Pedig nem invalid a css amit commitoltam.  Node 6-al is elojon?

Gondolom egy `rm -rf node_modules tmp bower_components; npm install; bower install` megoldja, nem? De lehet eleg a broccolit ujra telepiteni.

**Comment by csutorasr** [comment]
A parancsok nem oldottak meg, es az `npm install` ujboli futtatasa sem.

Fun fact: Az `npm install` mindig 118 csomagot rak fel, akarhanyszor futtatom le.

**Comment by lordblendi** [comment]
Az en commitom elotti valtozat jo? Nincsenek valahol invalid whitespace
karakterek?

Node 6 is ugyanez?

**Comment by csutorasr** [comment]
Node 6-tal ugyanaz, csak 114 package-t keszit.

```
Running without elevated rights. Running Ember CLI "as Administrator" increases performance significantly.
See ember-cli.com/user-guide/#windows for details.

Livereload server on http://localhost:49153
Serving on http://localhost:4200/
The Broccoli Plugin: [ConfigReplace] failed with:
Error: ENOENT: no such file or directory, lstat 'C:\Users\Csuto\Documents\projects\szglab5-main\frontend\tmp\funnel-input_base_path-XlAH6ecS.tmp\index.html'
    at Error (native)
    at Object.fs.lstatSync (fs.js:995:11)
    at symlinkWindows (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\symlink-or-copy\index.js:106:25)
    at Function.symlinkOrCopySync [as sync] (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\symlink-or-copy\index.js:63:5)
    at Funnel._copy (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\broccoli-funnel\index.js:492:19)
    at Funnel.processFile (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\broccoli-funnel\index.js:475:8)
    at Funnel.applyPatch [as _applyPatch] (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\broccoli-funnel\index.js:389:12)
    at Funnel.<anonymous> (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\broccoli-funnel\index.js:343:10)
    at Array.forEach (native)
    at Funnel.processFilters (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\broccoli-funnel\index.js:342:11)

The broccoli plugin was instantiated at:
    at ConfigReplace.Plugin (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\broccoli-plugin\index.js:7:31)
    at new ConfigReplace (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\broccoli-config-replace\index.js:13:10)
    at EmberApp.testIndex (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\ember-cli\lib\broccoli\ember-app.js:782:10)
    at EmberApp.toArray (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\ember-cli\lib\broccoli\ember-app.js:1681:43)
    at EmberApp.toTree (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\ember-cli\lib\broccoli\ember-app.js:1696:30)
    at module.exports (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\ember-cli-build.js:26:14)
    at CoreObject.setupBroccoliBuilder (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\ember-cli\lib\models\builder.js:84:19)
    at CoreObject.init (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\ember-cli\lib\models\builder.js:64:10)
    at CoreObject.superWrapper [as init] (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\ember-cli\node_modules\core-object\lib\assign-properties.js:32:18)
    at CoreObject.Class (C:\Users\Csuto\Documents\projects\szglab5-main\frontend\node_modules\ember-cli\node_modules\core-object\core-object.js:32:33)
```

**Comment by lordblendi** [comment]
Az index.html fajl nem hianyzik? Az app es a tests mappakbol

**Comment by csutorasr** [comment]
A `tests` mappa kitorlese megoldotta a problemat.
